eval "$(/opt/homebrew/bin/brew shellenv)"

# Homebrew: hide env hints (e.g. HOMEBREW_AUTO_UPDATE_SECS, HOMEBREW_NO_INSTALL_CLEANUP)
export HOMEBREW_NO_ENV_HINTS=1

export PATH=/opt/homebrew/bin:$PATH

code () { VSCODE_CWD="$PWD" open -n -b "com.microsoft.VSCode" --args $* ;}

#------------------------------------------------------------
#   Command prompt
#------------------------------------------------------------
# Zsh equivalent of bash PS1 - shows full path
PROMPT='%F{cyan}%/%f $ '

#------------------------------------------------------------
#   Set Paths
#------------------------------------------------------------
export ANDROID_HOME=~/Library/Android/sdk
export GEM_HOME=$HOME/.gem
export PATH=$GEM_HOME/bin:$PATH
export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin
export PATH="$PATH:/usr/local/bin/"
export PATH="$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:/usr/local/git/bin:/sw/bin/:/usr/local/bin:/usr/local/:/usr/local/sbin:/usr/local/mysql/bin:$PATH"

#   Set Default Editor
#------------------------------------------------------------
export EDITOR=/usr/bin/nano

#   Set default blocksize for ls, df, du
#------------------------------------------------------------
export BLOCKSIZE=1k

#   Add color to terminal
#------------------------------------------------------------
export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad

# Fix for Python ValueError: unknown locale: UTF-8
#------------------------------------------------------------
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

#------------------------------------------------------------
#   Zsh VCS Info (Git branch display)
#------------------------------------------------------------
autoload -Uz vcs_info
precmd_vcs_info() { vcs_info }
precmd_functions+=( precmd_vcs_info )
setopt prompt_subst
RPROMPT=\$vcs_info_msg_0_
zstyle ':vcs_info:git:*' formats '%F{240}(%b)%r%f'
zstyle ':vcs_info:*' enable git

#------------------------------------------------------------
#   MAKE TERMINAL BETTER
#------------------------------------------------------------
alias cp='cp -iv'                           # Preferred 'cp' implementation
alias mv='mv -iv'                           # Preferred 'mv' implementation
alias mkdir='mkdir -pv'                     # Preferred 'mkdir' implementation
#alias ll='ls -alFG'
alias ll='ls -FGlAhp'                       # Preferred 'ls' implementation
alias ls='ls -F'                            # -F appends a character revealing the nature of a file, for example, * for an executable, or / for a directory. Regular files have no suffix.
alias less='less -FSRXc'                    # Preferred 'less' implementation
cd() { builtin cd "$@"; ll; }               # Always list directory contents upon 'cd'
alias cd..='cd ../'                         # Go back 1 directory level (for fast typers)
alias ..='cd ../'                           # Go back 1 directory level
alias ...='cd ../../'                       # Go back 2 directory levels
alias .3='cd ../../../'                     # Go back 3 directory levels
alias .4='cd ../../../../'                  # Go back 4 directory levels
alias .5='cd ../../../../../'               # Go back 5 directory levels
alias .6='cd ../../../../../../'            # Go back 6 directory levels
alias edit='atom'                           # edit:         Opens any file in atom/Visual studio code
alias f='open -a Finder ./'                 # f:            Opens current directory in MacOS Finder
alias ~="cd ~"                              # ~:            Go Home
alias c='clear'                             # c:            Clear terminal display
alias which='type -all'                     # which:        Find executables
alias path='echo -e ${PATH//:/\\n}'         # path:         Echo all executable Paths
alias show_options='setopt'                 # Show_options: display zsh options settings (zsh equivalent of shopt)
alias fix_stty='stty sane'                  # fix_stty:     Restore terminal settings when screwed up
alias cic='setopt CASE_GLOB'                # cic:          Make tab-completion case-insensitive (zsh equivalent)
mcd () { mkdir -p "$1" && cd "$1"; }        # mcd:          Makes new Dir and jumps inside
trash () { command mv "$@" ~/.Trash ; }     # trash:        Moves a file to the MacOS trash
ql () { qlmanage -p "$*" >& /dev/null; }    # ql:           Opens any file in MacOS Quicklook Preview
alias DT='tee ~/Desktop/terminalOut.txt'    # DT:           Pipe content to file on MacOS Desktop
alias showFiles='defaults write com.apple.finder AppleShowAllFiles YES; killall Finder /System/Library/CoreServices/Finder.app'
alias hideFiles='defaults write com.apple.finder AppleShowAllFiles NO; killall Finder /System/Library/CoreServices/Finder.app'
alias gPull='ls | xargs -P10 -I{} git -C {} pull'

#------------------------------------------------------------
#  Zsh completions
#------------------------------------------------------------
# Enable zsh completions
autoload -Uz compinit
compinit

#------------------------------------------------------------
#  Docker
#------------------------------------------------------------
#docker-machine start default
#VM_NAME=default
#if [ "$(docker-machine status $VM_NAME)" == "Running" ]; then
#  echo "Setting environment variables for docker-machine $VM_NAME..."
#  eval "$(docker-machine env $VM_NAME)"
#fi
alias cleanContainers='docker rm `docker ps -aq -f status=exited`'
alias listContainers='docker ps -a'

export DOCKERCLOUD_NAMESPACE=hiotlabs

#------------------------------------------------------------
#   NETWORKING
#------------------------------------------------------------
alias myip='curl ifconfig.co'                    # myip:         Public facing IP Address
alias netCons='lsof -i'                             # netCons:      Show all open TCP/IP sockets
alias flushDNS='dscacheutil -flushcache'            # flushDNS:     Flush out the DNS Cache
alias lsock='sudo /usr/sbin/lsof -i -P'             # lsock:        Display open sockets
alias lsockU='sudo /usr/sbin/lsof -nP | grep UDP'   # lsockU:       Display only open UDP sockets
alias lsockT='sudo /usr/sbin/lsof -nP | grep TCP'   # lsockT:       Display only open TCP sockets
alias ipInfo0='ipconfig getpacket en0'              # ipInfo0:      Get info on connections for en0
alias ipInfo1='ipconfig getpacket en1'              # ipInfo1:      Get info on connections for en1
alias openPorts='sudo lsof -i | grep LISTEN'        # openPorts:    All listening connections
alias showBlocked='sudo ipfw list'                  # showBlocked:  All ipfw rules inc/ blocked IPs

#   ii:  display useful host related informaton
#------------------------------------------------------------
ii() {
    echo -e "\nYou are logged on ${RED}$HOST"
    echo -e "\nAdditionnal information:$NC " ; uname -a
    echo -e "\n${RED}Users logged on:$NC " ; w -h
    echo -e "\n${RED}Current date :$NC " ; date
    echo -e "\n${RED}Machine stats :$NC " ; uptime
    echo -e "\n${RED}Current network location :$NC " ; scselect
    echo -e "\n${RED}Public facing IP Address :$NC " ;myip
    #echo -e "\n${RED}DNS Configuration:$NC " ; scutil --dns
    echo
}

#------------------------------------------------------------
#   PROCESS MANAGEMENT
#------------------------------------------------------------
#   findPid: find out the pid of a specified process
#------------------------------------------------------------
#       Note that the command name can be specified via a regex
#       E.g. findPid '/d$/' finds pids of all processes with names ending in 'd'
#       Without the 'sudo' it will only find processes of the current user
#------------------------------------------------------------
findPid () { lsof -t -c "$@" ; }
#   memHogsTop, memHogsPs:  Find memory hogs
#------------------------------------------------------------
alias memHogsTop='top -l 1 -o rsize | head -20'
alias memHogsPs='ps wwaxm -o pid,stat,vsize,rss,time,command | head -10'

#   cpuHogs:  Find CPU hogs
#------------------------------------------------------------
alias cpu_hogs='ps wwaxr -o pid,stat,%cpu,time,command | head -10'

#   topForever:  Continual 'top' listing (every 10 seconds)
#------------------------------------------------------------
alias topForever='top -l 9999999 -s 10 -o cpu'

#   ttop:  Recommended 'top' invocation to minimize resources
#------------------------------------------------------------
#       Taken from this macosxhints article
#       http://www.macosxhints.com/article.php?story=20060816123853639
#------------------------------------------------------------
alias ttop="top -R -F -s 10 -o rsize"

#   my_ps: List processes owned by my user:
#------------------------------------------------------------
my_ps() { ps $@ -u $USER -o pid,%cpu,%mem,start,time,bsdtime,command ; }

#------------------------------------------------------------
#   DEV MANAGEMENT
#------------------------------------------------------------
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/jonasdeibe/hiotlabs/google-cloud-sdk/path.bash.inc' ]; then source '/Users/jonasdeibe/hiotlabs/google-cloud-sdk/path.bash.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/jonasdeibe/hiotlabs/google-cloud-sdk/completion.bash.inc' ]; then source '/Users/jonasdeibe/hiotlabs/google-cloud-sdk/completion.bash.inc'; fi

# Added by OrbStack: command-line tools and integration
# This won't be added again if you remove it.
source ~/.orbstack/shell/init.zsh 2>/dev/null || :
